# Generated by Django 4.2.1 on 2023-06-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Articulo',
        ),
        migrations.AlterModelTable(
            name='articulo',
            table=None,
        ),
    ]
