# Generated by Django 4.2.1 on 2023-06-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'sugerencia']], default=0)),
                ('mensage', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
    ]
