# Generated by Django 4.2.1 on 2023-06-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoweb', '0002_contacro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacro',
            new_name='Contacto',
        ),
    ]
