# Generated by Django 4.2.1 on 2023-06-02 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoweb', '0003_rename_contacro_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
    ]
